### ISSUE TITLE
Non-CocoaPods integration

### ISSUE THREAD

**Issue by gyulavoros** [google-ar/arcore-ios-sdk#58]
We have a specific project setup that is not really compatible with CocoaPods (we use [Xcodegen](https://github.com/yonaskolb/XcodeGen)).

Other Google products have various ways to integrate them, e.g., [Firebase supports](https://firebase.google.com/docs/ios/installation-methods) SPM, CocoaPods, Carthage, and manual integration. Google Maps has the [same options](https://developers.google.com/maps/documentation/ios-sdk/config#download-sdk).

From our perspective, some distribution of `xcframeworks` would be best, so the project is also compatible with the latest M1 and M2 MacBooks and Apple Silicon.

Some open-source projects publish binaries in their GitHub Releases section, e.g., RxSwift has `xcframeworks` [available here](https://github.com/ReactiveX/RxSwift/releases/tag/6.5.0).

May we expect any alternatives anytime soon?

**Comment by jrullman** [comment]
ARCore 1.33 was just released, and it includes XCFramework binaries with arm64 simulator architecture included.
It also includes beta support for Swift Package Manager - you can download the pod bundle and integrate it as a local Swift Package, following the directions in the bundled README file.

In general I would not recommend manual integration. You would need to get all the transitive dependencies, resource bundles, etc. correctly, and there are a lot of ways to mess up. That's why things like CocoaPods and SPM exist in the first place.
