### ISSUE TITLE
Can't seem to resolve anchors

### ISSUE THREAD

**Issue by Jacquelinett** [google-ar/arcore-ios-sdk#9]
Hi, I'm not sure if I am doing something wrong, but the same function I wrote that used to be able to resolve anchors can't seem to resolve anchor anymore.  I changed my program from single view app to multiple view, but the anchor loading function stayed the same. I even tried to revert my changes, but it doesn't seem like that work anymore.

All I am doing right now to load is essentially these two functions:

`
- (void) loadAnchor: (NSString *) anchorID {
    [self resolveAnchorWithIdentifier:anchorID];
}

- (void)resolveAnchorWithIdentifier:(NSString *)identifier {
    self.garAnchor = [self.gSession resolveCloudAnchorWithIdentifier:identifier error:nil];
}`

When the program is loaded, I connect to the database to get the list of all anchorIdentifier saved, and loop through them and call loadAnchor(anchor) for each.

Again, these same function worked before, but for some reason after changed to multiview (by adding more view controllers and add segue to reach the ExampleViewController) so I'm not sure if that would affect the ARCore at all. 

Any suggestion?

EDIT:

I modified the touchEnded a little bit to try to resolve anchor again when is in StateResolving to attempt to load again and it seem to load, maybe I needed to wait a little bit before I attempt to resolve anchors?

EDIT 2:

I think I figured out why, my loadAnchor apparently get executed before ViewWillAppear is executed, so I just need to figure out how to wait for that to run. I'm going to close the issue. Thank!

**Comment by sammcd** [comment]
I'm glad you were able to solve the problem. You aren't the first person to be tripped up by this, so I will look into seeing how we could improve this or at least our documentation.

Thanks!

**Comment by Jacquelinett** [comment]
Thank for replying!

Let me clarify something real quick so you don't have to go through the same problem if you are attempting to come up with a solution. I tried to load the anchor in ViewDidAppear (which is the latest in the cycle before ViewWillDisappear) and it doesn't work either. What I ended up doing were using a timer inside of ViewDidAppear instead to make it work:

`- (void)viewDidAppear:(BOOL)animated {
    [NSTimer scheduledTimerWithTimeInterval:2.0
                                     target:self
                                   selector:@selector(loadRoom)
                                   userInfo:nil
                                    repeats:NO];
}`

**Comment by sammcd** [comment]
This timer approach will work, but if it is helpful what you are really wanting to wait for is ARKit's camera tracking state to be a in a good state. You could also wait for this property (https://developer.apple.com/documentation/arkit/arcamera/2880259-trackingstate?language=objc) to be `ARTrackingStateNormal`. The reason your app has to wait is because in viewDidAppear ARKit has not had enough time to view your surroundings and get into a good state.

If you don't want to wait for that property there is also a delegate method that gets called when the camera's tracking state changes here: https://developer.apple.com/documentation/arkit/arsessionobserver/2887450-session?language=objc
